// Car horn test suite.
//
// Verifies the four synthesized horn OGGs (generated by tools/make-horns.py)
// are present, decodable, and spectrally correct: for each design frequency
// (the horn's fundamental tones) the Goertzel power at that frequency must
// dominate detuned probe frequencies either side — i.e., the file actually
// honks at the pitch it was designed for. Also proves the generator still
// runs clean (regeneration into a temp dir).
//
//   1. All four horn files exist in audio/ with sane sizes
//   2. Each decodes via ffmpeg and its design fundamentals dominate
//   3. tools/make-horns.py regenerates all four without error
//
// Run: node test-horns.mjs

import { execFileSync } from 'node:child_process';
import { existsSync, statSync, mkdtempSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

let passed = 0, failed = 0;
function test( name, cond, detail = '' ) {

	if ( cond ) { passed++; console.log( `  ✓ ${ name }` ); }
	else { failed++; console.error( `  ✗ ${ name }${ detail ? ' — ' + detail : '' }` ); }

}

const SR = 44100;
const VARIANTS = {
	'classic': [ 420, 500 ],
	'truck': [ 233, 350 ],
	'sport': [ 545, 660 ],
	'compact': [ 620 ],
};

console.log( '--- Committed horn files ---' );

{
	let allFiles = true, allDecoded = true, allPeaks = true;
	for ( const [ variant, fundamentals ] of Object.entries( VARIANTS ) ) {

		const file = `audio/horn-${ variant }.ogg`;
		if ( ! existsSync( file ) ) { allFiles = false; test( `${ file } exists`, false ); continue; }
		const kb = statSync( file ).size / 1024;
		if ( kb < 2 ) { allFiles = false; test( `${ file } sane size`, false, `${ kb.toFixed( 1 ) }KB` ); continue; }

		// Decode to 16-bit mono WAV and extract samples.
		let samples;
		try {

			const buf = execFileSync( 'ffmpeg', [ '-loglevel', 'error', '-i', file, '-ac', '1', '-ar', String( SR ), '-f', 'wav', '-' ], { maxBuffer: 8 * 1024 * 1024 } );
			// Minimal RIFF walk: find the 'data' chunk.
			let off = 12;
			while ( off + 8 <= buf.length ) {

				const id = buf.toString( 'ascii', off, off + 4 );
				const size = buf.readUInt32LE( off + 4 );
				if ( id === 'data' ) {

					// The final chunk can claim bytes past the buffer — clamp.
					const avail = Math.min( size, buf.length - ( off + 8 ) );
					const n = Math.floor( avail / 2 );
					samples = new Float64Array( n );
					for ( let i = 0; i < n; i ++ ) samples[ i ] = buf.readInt16LE( off + 8 + i * 2 ) / 32768;
					break;

				}
				off += 8 + size + ( size % 2 );

			}

		} catch ( err ) { allDecoded = false; test( `${ file } decodes`, false, err.message ); continue; }
		if ( ! samples ) { allDecoded = false; test( `${ file } has PCM data`, false ); continue; }

		// Analyze the sustained middle of the honk (skip attack, stop before release).
		const from = Math.floor( 0.15 * SR );
		const to = Math.min( Math.floor( 0.5 * SR ), samples.length - 1 );
		const seg = samples.subarray( from, to );
		if ( seg.length < SR / 10 ) { allDecoded = false; test( `${ file } long enough`, false ); continue; }

		// Goertzel power at a target frequency vs detuned probes either side.
		const goertzel = ( freq ) => {

			const k = 2 * Math.PI * freq / SR;
			const coeff = 2 * Math.cos( k );
			let s1 = 0, s2 = 0;
			for ( let i = 0; i < seg.length; i ++ ) {

				const s0 = seg[ i ] + coeff * s1 - s2;
				s2 = s1; s1 = s0;

			}
			return s1 * s1 + s2 * s2 - coeff * s1 * s2;

		};
		for ( const f0 of fundamentals ) {

			const at = goertzel( f0 );
			const low = goertzel( f0 * 0.93 );
			const high = goertzel( f0 * 1.07 );
			const ok = at > 5 * low && at > 5 * high;
			if ( ! ok ) { allPeaks = false; test( `${ variant }: ${ f0 } Hz dominates`, false, `power ${ at.toFixed( 1 ) } vs probes ${ low.toFixed( 1 ) }/${ high.toFixed( 1 ) }` ); }
			else test( `${ variant }: ${ f0 } Hz dominates`, true );

		}

	}
	if ( allFiles && allDecoded && allPeaks ) test( 'all four horns present, decodable, spectrally correct', true );
}

console.log( '--- Generator still runs clean ---' );

{
	try {

		const tmp = mkdtempSync( join( tmpdir(), 'skid-horns-' ) );
		execFileSync( 'python3', [ 'tools/make-horns.py', '--out', tmp ], { stdio: 'pipe' } );
		const files = readdirSync( tmp ).filter( ( f ) => f.endsWith( '.ogg' ) ).sort();
		test( 'regenerates all four horns', files.length === 4, files.join( ', ' ) );

	} catch ( err ) {

		test( 'generator runs clean', false, err.message );

	}
}

console.log( `\n${ passed } passed, ${ failed } failed${ failed ? ' — WITH FAILURES' : '' }` );
process.exitCode = failed ? 1 : 0;
